### ISSUE TITLE
Handle existing folders better

### ISSUE THREAD

**Issue by MiniGod** [tiezhu92/faster-webpack-upload-plugin#2]
I have quite a big `dist` folder with lots of files and folders, so it spits out a lot of warning about "Folder create failed,it might exists". Which is true, all the folders exist.

I preferably want to always run with `firstEmit: false` so only uploads assets as they complete, but then it doesn't ensure the folders exist.

![image](https://user-images.githubusercontent.com/60520/54035481-628dfc80-41b1-11e9-9c92-87fac10b8a72.png)

**Comment by tiezhu92** [comment]
Thank for you issue!
But in my opinion, "cache" code for the folders is hard to run correctly, because when you modify files directly from the server, the cache will be wrong.
To ensure the correctness of the cache folders, it must confirm to the server whether it exists or not, so that cache was useless.
I can add a folder check before "not firstEmit" code, but the plugin will slow down.
In conclusion, i prefer to add options to ignore the warning,i can't think of a better way at this time.

**Comment by MiniGod** [comment]
I mentioned I'd want to run this with `firstEmit: false` always. What I meant by that is that I do not want to run the initial synchronization of the dist folder. It makes more sense to me to just upload emitted assets. That's why I wanted to fix it in a way that ensured the folders were created even if it didn't do the initial sync.

Another solution could be to simply assume the folders exist. Then if the `fastPut` call fails, it would create the folders. Would the error from `fastPut` indicate that the failure was caused by the folder not existing?

**Comment by tiezhu92** [comment]
OK, i will handle this next day
